### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [riteshtheking/audio-player#1]
Hello, i am a graphic designer. I would love to contribute a logo design for your project and it's free. Thanks for your urgent reply.

**Comment by riteshtheking** [comment]
Sure we will love to

**Comment by dee-y** [comment]
Hi, what do you think of this design, any color preferations, or font changes, or other modifications you might want me to make? if you are satisfactory with the design, what sizes of logo do you want me to export for you?

![audio player-01](https://user-images.githubusercontent.com/36637989/43293950-d681b3da-9134-11e8-92af-6a30ac732daa.png)

**Comment by riteshtheking** [comment]
Thanks man, you did for us well i will use it for sure... 
And it's ossam... 
Well, i think it will be ossam to work with you...
